AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/AlignArray:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/IndentationWidth:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/ReturnInVoidContext:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
