 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Run RSpec
          command: bundle exec rspec
